// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIQXVvGla-KlqXjmSUF-UIEX8EcXPbLtU',
    appId: '1:407177118907:web:351b30471a8f99b229159e',
    messagingSenderId: '407177118907',
    projectId: 'chitchatapp-6ada7',
    authDomain: 'chitchatapp-6ada7.firebaseapp.com',
    storageBucket: 'chitchatapp-6ada7.appspot.com',
    measurementId: 'G-W7EPWG5TZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1JQl1_UujWkuuUh2uWPayqXsjaMN4c0E',
    appId: '1:407177118907:android:a6db9dc0e7826d0129159e',
    messagingSenderId: '407177118907',
    projectId: 'chitchatapp-6ada7',
    storageBucket: 'chitchatapp-6ada7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3kBBiZeG8jtvjtBhv85vONOaSYrqXr8o',
    appId: '1:407177118907:ios:7497b54977e5a90529159e',
    messagingSenderId: '407177118907',
    projectId: 'chitchatapp-6ada7',
    storageBucket: 'chitchatapp-6ada7.appspot.com',
    androidClientId: '407177118907-e1fr6k4cenv8u2oa0qbi938bghd080ki.apps.googleusercontent.com',
    iosClientId: '407177118907-ujbdltdr3l4emlsco4p9ukqlo6nnrn87.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3kBBiZeG8jtvjtBhv85vONOaSYrqXr8o',
    appId: '1:407177118907:ios:eb60770412680aa229159e',
    messagingSenderId: '407177118907',
    projectId: 'chitchatapp-6ada7',
    storageBucket: 'chitchatapp-6ada7.appspot.com',
    androidClientId: '407177118907-e1fr6k4cenv8u2oa0qbi938bghd080ki.apps.googleusercontent.com',
    iosClientId: '407177118907-b4461n4b6998e2l8u9h8b8j47sjct3f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitchat.RunnerTests',
  );
}
